name: lint, test, build
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production
        run: npm run build:prod
      - name: lint typescript
        run: npm run lint:ts
      - name: lint scss
        run: npm run lint:scss
#        Временно пропускаем юнит тесты, ошибка с глобальнымим импортами
#      - name: unit testing
#        run: npm run unit
      - name: storybook build
        run: npm run storybook:build


